[package]
name = "bdk-starter-example"
version = "0.1.0"
edition = "2024"

[dependencies]
bdk_wallet = { version = "2.1.0", features = ["rusqlite"] }
bdk_esplora = { version = "0.22.1", features = ["blocking"] }
